# Generated by Django 6.0.1 on 2026-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trend',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trend',
            name='score',
            field=models.FloatField(),
        ),
    ]
